### ISSUE TITLE
failed to add BLV

### ISSUE THREAD

**Issue by seamxr** [seamxr/dividend#10]

**Comment by seamxr** [comment]
Likely because:
2019/09/09 04:39:18 http: panic serving 184.66.44.110:51659: runtime error: invalid memory address or nil pointer dereference
goroutine 1259 [running]:
net/http.(*conn).serve.func1(0xc0005226e0)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x900020, 0xef2fb0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/seamxr/dividend/datasource/utils.ExtractValuesFromDataTable(0xc000538f50, 0xc0005d2d80, 0x97c126, 0x2)
        /opt/app/src/datasource/utils/utils.go:29 +0x70
github.com/seamxr/dividend/datasource/basicdata.extractSummaryDoublePanels(0xc0005d6000, 0xc0005d2d80, 0x0, 0x0)

**Comment by seamxr** [comment]
fixed
